server:
  port: 8083
spring:
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://inventory-db:5432/inventory}
    username: ${INVENTORY_DB_USERNAME:inventory}
    password: ${INVENTORY_DB_PASSWORD:inventory}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.shopscale.inventory.domain.event.OrderPlacedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      observation-enabled: true
  flyway:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
app:
  timeout-ms: ${INVENTORY_TIMEOUT_MS:3000}
